# Generated by Django 4.2.10 on 2024-05-11 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('type', models.CharField(choices=[('tuition_fee', 'Tuition Fee'), ('salary', 'Salary')], max_length=31, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Amount')),
                ('paid_month', models.DateField(default=django.utils.timezone.now, verbose_name='Paid Date')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Monthly Payment',
                'verbose_name_plural': 'Monthly Payments',
            },
        ),
    ]
