# Generated by Django 4.2.10 on 2024-05-13 04:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_expensetype_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='paid_date',
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
