# Generated by Django 4.2.10 on 2024-06-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_remove_expense_paid_date_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayment',
            name='calculated_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Calculated Salary'),
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='present_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Present Days'),
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='total_working_hours',
            field=models.IntegerField(blank=True, help_text='Worker should work that amount of hours in a month to get full salary', null=True, verbose_name='Total Working Hours'),
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='worked_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Worked Hours'),
        ),
    ]
