# Generated by Django 4.2.10 on 2024-06-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_monthlypayment_calculated_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlypayment',
            name='total_working_hours',
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='total_working_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Working Days'),
        ),
    ]
