# Generated by Django 4.2.10 on 2024-06-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_remove_monthlypayment_total_working_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayment',
            name='is_notified',
            field=models.BooleanField(default=False, verbose_name='Is Notified'),
        ),
    ]
