# Generated by Django 4.2.10 on 2024-06-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_monthlypayment_is_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayment',
            name='full_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Full Salary'),
        ),
    ]
