# Generated by Django 4.2.10 on 2024-05-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceIDSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_device_ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='Enter device IP')),
                ('enter_device_last_sync_time', models.DateTimeField(blank=True, null=True, verbose_name='Enter device last sync time')),
                ('enter_device_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Enter device username')),
                ('enter_device_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Enter device password')),
                ('exit_device_ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='Exit device IP')),
                ('exit_device_last_sync_time', models.DateTimeField(blank=True, null=True, verbose_name='Exit device last sync time')),
                ('exit_device_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Exit device username')),
                ('exit_device_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Exit device password')),
            ],
            options={
                'verbose_name': 'Face ID settings',
                'verbose_name_plural': 'Face ID settings',
            },
        ),
    ]
