# Generated by Django 4.2.10 on 2024-05-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_faceidsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceidsettings',
            name='enter_last_run',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enter last run'),
        ),
        migrations.AddField(
            model_name='faceidsettings',
            name='exit_last_run',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Exit last run'),
        ),
    ]
