# Generated by Django 4.2.10 on 2024-05-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_gender_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceidlog',
            name='log_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Log Data'),
        ),
        migrations.AddField(
            model_name='faceidlog',
            name='type',
            field=models.CharField(blank=True, choices=[('enter', 'Enter'), ('exit', 'Exit')], max_length=31, null=True, verbose_name='Type'),
        ),
    ]
