# Generated by Django 4.2.10 on 2024-05-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_faceidlog_log_data_faceidlog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceidlog',
            name='serial_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Serial No'),
        ),
    ]
