# Generated by Django 4.2.10 on 2024-05-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_faceidlog_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_id',
            field=models.CharField(max_length=255, null=True, verbose_name='Face ID'),
        ),
    ]
