# Generated by Django 4.2.10 on 2024-06-03 16:15

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_face_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceidlog',
            name='is_notified',
            field=models.BooleanField(default=False, verbose_name='Is Notified'),
        ),
        migrations.AddField(
            model_name='faceidlog',
            name='notification_log',
            field=models.JSONField(blank=True, null=True, verbose_name='Notification Log'),
        ),
        migrations.AddField(
            model_name='user',
            name='parents_tg_ids',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=31, null=True), blank=True, null=True, size=None, verbose_name='Parents Telegram IDs'),
        ),
    ]
