# Generated by Django 4.2.10 on 2024-06-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_faceidlog_is_notified_faceidlog_notification_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceidlog',
            name='notification_log',
            field=models.TextField(blank=True, null=True, verbose_name='Notification Log'),
        ),
    ]
