# Generated by Django 4.2.10 on 2024-06-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_faceidlog_notification_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enter_image_sync_data',
            field=models.TextField(blank=True, null=True, verbose_name='Enter Image Sync Data'),
        ),
        migrations.AddField(
            model_name='user',
            name='enter_terminal_sync_data',
            field=models.TextField(blank=True, null=True, verbose_name='Enter Terminal Sync Data'),
        ),
        migrations.AddField(
            model_name='user',
            name='exit_image_sync_data',
            field=models.TextField(blank=True, null=True, verbose_name='Exit Image Sync Data'),
        ),
        migrations.AddField(
            model_name='user',
            name='exit_terminal_sync_data',
            field=models.TextField(blank=True, null=True, verbose_name='Exit Terminal Sync Data'),
        ),
        migrations.AddField(
            model_name='user',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='face_images', verbose_name='Face Image'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_enter_image_synced',
            field=models.BooleanField(default=False, verbose_name='Is Image Synced with Enter Terminal'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_enter_terminal_synced',
            field=models.BooleanField(default=False, verbose_name='Is Synced with Enter Terminal'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_exit_image_synced',
            field=models.BooleanField(default=False, verbose_name='Is Image Synced with Exit Terminal'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_exit_terminal_synced',
            field=models.BooleanField(default=False, verbose_name='Is Synced with Exit Terminal'),
        ),
    ]
