# Generated by Django 4.2.10 on 2024-06-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_enter_image_sync_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='face_image',
            field=models.ImageField(blank=True, help_text='Image size should be less than 200KB', null=True, upload_to='face_images', verbose_name='Face Image'),
        ),
    ]
