# Generated by Django 4.2.10 on 2024-06-10 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_salary_userpresence'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpresence',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userpresence',
            unique_together={('user', 'date')},
        ),
    ]
