# Generated by Django 4.2.10 on 2024-06-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userpresence_date_alter_userpresence_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpresence',
            name='enter_at',
            field=models.TimeField(blank=True, null=True, verbose_name='Enter at'),
        ),
        migrations.AlterField(
            model_name='userpresence',
            name='exit_at',
            field=models.TimeField(blank=True, null=True, verbose_name='Exit at'),
        ),
    ]
