# Generated by Django 4.2.10 on 2024-06-10 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_userpresence_enter_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpresence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_presences', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
