# Generated by Django 4.2.10 on 2024-06-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_userpresence_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Work End Time'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Work Start Time'),
        ),
        migrations.AddField(
            model_name='userpresence',
            name='total_working_hours',
            field=models.FloatField(default=0, help_text='in hours', verbose_name='Total Working Hours'),
        ),
        migrations.AddField(
            model_name='userpresence',
            name='work_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Work End Time'),
        ),
        migrations.AddField(
            model_name='userpresence',
            name='work_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Work Start Time'),
        ),
        migrations.AlterField(
            model_name='userpresence',
            name='present_time',
            field=models.FloatField(default=0, help_text='in hours', verbose_name='Present Time'),
        ),
    ]
