# Generated by Django 4.2.10 on 2024-06-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_work_end_time_user_work_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceidlog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='face_id_logs', verbose_name='Image'),
        ),
    ]
