# Generated by Django 4.2.10 on 2024-06-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_faceidlog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tuition_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Tuition Fee'),
        ),
    ]
