# Generated by Django 4.2.10 on 2024-07-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_tuition_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceidlog',
            name='is_notified_teacher',
            field=models.BooleanField(default=False, verbose_name='Is Notified Teacher'),
        ),
        migrations.AlterField(
            model_name='faceidlog',
            name='is_notified',
            field=models.BooleanField(default=False, verbose_name='Is Notified Parent'),
        ),
    ]
