# Generated by Django 4.2.10 on 2024-06-09 15:30

import django.core.validators
from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('worker_type', models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('educator', 'Educator'), ('kindergartener', 'Kindergartener'), ('worker', 'Worker')], max_length=31, verbose_name='Type')),
                ('month', models.DateField(verbose_name='Month')),
                ('work_days', django_jsonform.models.fields.ArrayField(base_field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]), blank=True, null=True, size=None, verbose_name='Work Days')),
                ('daily_work_hours', models.IntegerField(verbose_name='Daily Work Hours')),
            ],
            options={
                'verbose_name': 'Work Calendar',
                'verbose_name_plural': 'Work Calendars',
                'unique_together': {('worker_type', 'month')},
            },
        ),
    ]
