# Generated by Django 4.2.10 on 2024-06-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_workcalendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHourSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start_time', models.TimeField(verbose_name='Work Start Time')),
                ('work_end_time', models.TimeField(verbose_name='Work End Time')),
                ('last_calculation_date', models.DateField(blank=True, null=True, verbose_name='Last Calculation Date')),
            ],
            options={
                'verbose_name': 'Working Hour Settings',
                'verbose_name_plural': 'Working Hour Settings',
            },
        ),
    ]
