# Generated by Django 4.2.10 on 2024-06-10 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_workinghoursettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghoursettings',
            name='work_end_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Work End Time'),
        ),
        migrations.AlterField(
            model_name='workinghoursettings',
            name='work_start_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Work Start Time'),
        ),
    ]
