# Generated by Django 4.2.10 on 2024-06-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_workinghoursettings_work_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workcalendar',
            name='daily_work_hours',
        ),
        migrations.RemoveField(
            model_name='workinghoursettings',
            name='work_end_time',
        ),
        migrations.RemoveField(
            model_name='workinghoursettings',
            name='work_start_time',
        ),
    ]
