# Generated by Django 4.2.10 on 2024-07-15 05:18

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_remove_workcalendar_daily_work_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educatinggroup',
            name='teachers_tg_ids',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=31, null=True), blank=True, null=True, size=None, verbose_name='Teachers Telegram IDs'),
        ),
    ]
